// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixTreeViewer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsixTreeViewerString = "94a107f4-c5c9-4926-beeb-a04becb558e5";
        public static Guid VsixTreeViewer = new Guid(VsixTreeViewerString);

        public const string HasVsixProjectString = "d2f31508-a26d-4838-ad63-8dc0adac8de3";
        public static Guid HasVsixProject = new Guid(HasVsixProjectString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}
